import { jsPDF } from 'jspdf';
import type { ChecklistResult } from '../types';

export function generateChecklistPdf(checklist: ChecklistResult): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  const addLine = (text: string, fontSize: number, bold = false) => {
    doc.setFontSize(fontSize);
    if (bold) {
      doc.setFont('helvetica', 'bold');
    } else {
      doc.setFont('helvetica', 'normal');
    }

    const lines = doc.splitTextToSize(text, pageWidth - 40);
    for (const line of lines) {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      doc.text(line, 20, y);
      y += fontSize * 0.5;
    }
    y += 4;
  };

  const addCheckbox = (text: string, checked = false) => {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    const box = checked ? '[x]' : '[ ]';
    const lines = doc.splitTextToSize(`${box} ${text}`, pageWidth - 45);
    for (const line of lines) {
      doc.text(line, 25, y);
      y += 6;
    }
    y += 2;
  };

  // Header
  addLine('VoterBridge - SAVE Act Registration Checklist', 16, true);
  addLine(`Scenario: ${checklist.scenarioLabel}`, 12, false);
  y += 4;

  // Warnings
  if (checklist.warnings.length > 0) {
    addLine('IMPORTANT NOTICES', 13, true);
    for (const warning of checklist.warnings) {
      addLine(`! ${warning}`, 10);
    }
    y += 4;
  }

  // Bridge documents
  if (checklist.bridgeDocumentsNeeded.length > 0) {
    addLine('BRIDGE DOCUMENTS NEEDED', 13, true);
    for (const bridgeDoc of checklist.bridgeDocumentsNeeded) {
      addCheckbox(bridgeDoc);
    }
    y += 4;
  }

  // Required documents
  addLine('DOCUMENTS TO BRING', 13, true);
  for (const req of checklist.requirements) {
    addCheckbox(req.document);
    if (req.proTip) {
      doc.setFontSize(9);
      doc.setFont('helvetica', 'italic');
      const tipLines = doc.splitTextToSize(`Tip: ${req.proTip}`, pageWidth - 50);
      for (const line of tipLines) {
        if (y > 270) {
          doc.addPage();
          y = 20;
        }
        doc.text(line, 30, y);
        y += 5;
      }
      y += 2;
    }
    if (req.alternatives && req.alternatives.length > 0) {
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      const altText = `Alternatives: ${req.alternatives.join(', ')}`;
      const altLines = doc.splitTextToSize(altText, pageWidth - 50);
      for (const line of altLines) {
        doc.text(line, 30, y);
        y += 5;
      }
      y += 2;
    }
  }

  // General tips
  y += 6;
  addLine('GENERAL TIPS', 13, true);
  const tips = [
    'Bring original documents - photocopies are usually rejected.',
    'Documents must have a raised seal or official certification stamp.',
    'Arrive early - offices may have long wait times near deadlines.',
    'Bring a pen with black ink for filling out forms.',
    'Have your Social Security Number memorized or written down separately.',
  ];
  for (const tip of tips) {
    addLine(`* ${tip}`, 10);
  }

  // Footer
  y += 10;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.text(
    'Generated by VoterBridge - Non-partisan civic tool. Verify all requirements with your local election office.',
    20,
    y
  );

  doc.save(`voterbridge-checklist-${Date.now()}.pdf`);
}
